package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestE2EOpenAPI verifies that apigen build with generate_openapi: true
// produces swagger.json files that are valid JSON and contain expected paths.
func TestE2EOpenAPI(t *testing.T) {
	// swagger.json is generated by `apigen build` into generated/openapi/.
	swaggerPath := filepath.Join("generated", "openapi", "library_service", "library_service.swagger.json")
	data, err := os.ReadFile(swaggerPath)
	if err != nil {
		t.Fatalf("read swagger.json: %v (did you run `apigen build`?)", err)
	}

	var spec map[string]any
	if err := json.Unmarshal(data, &spec); err != nil {
		t.Fatalf("swagger.json is not valid JSON: %v", err)
	}

	// Verify the swagger spec has a "paths" key.
	paths, ok := spec["paths"].(map[string]any)
	if !ok {
		t.Fatal("swagger.json missing or invalid 'paths' key")
	}

	// Verify the custom method path (AIP-136 colon syntax) is present.
	archivePath := "/library/LibraryService/book/{book_id}:archive"
	if _, ok := paths[archivePath]; !ok {
		t.Errorf("swagger.json paths missing custom method path %q; got paths: %v", archivePath, pathKeys(paths))
	}

	// Verify the overridden List path (GET) is present.
	listPath := "/library/LibraryService/book/meta/list"
	if _, ok := paths[listPath]; !ok {
		t.Errorf("swagger.json paths missing overridden List path %q; got paths: %v", listPath, pathKeys(paths))
	}
}

// pathKeys returns the keys of a paths map for error messages.
func pathKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	return keys
}
